/**
 * Live tests: real YouTube, real captions.
 *
 * Deliberately few, and spaced out; hammering YouTube from a suite is how an IP
 * gets throttled, and a throttled IP then makes the suite lie about the code.
 * Throttling therefore skips a test rather than failing it.
 *
 *   RUN_LIVE=1 pnpm vitest run test/live.test.ts
 */
import { describe, expect, it } from "vitest";

import { getTranscript, getVideoInfo, listLanguages } from "../src/service.js";
import { loadConfig } from "../src/config.js";
import { TranscriptError } from "../src/errors.js";

const RUN = process.env.RUN_LIVE === "1" || process.env.RUN_LIVE === "true";
const cfg = loadConfig({ ytDlp: "never", retries: 1, timeoutMs: 25_000 });

interface Ctx {
  skip: () => void;
}

const GAP = Number(process.env.LIVE_GAP_MS ?? 1200);
const wait = (ms: number = GAP) => new Promise((r) => setTimeout(r, ms));

const THROTTLED_CODES = new Set(["BOT_CHECK", "RATE_LIMITED", "NETWORK_ERROR", "TIMEOUT"]);
const THROTTLED_TEXT = /empty caption body|Every caption download path|not a bot|throttl/i;

function isThrottled(err: unknown): boolean {
  if (!(err instanceof TranscriptError)) return false;
  return THROTTLED_CODES.has(err.code) || THROTTLED_TEXT.test(err.message);
}

/** Run something, skipping the test if YouTube refused us rather than rejected us. */
async function attempt<T>(fn: () => Promise<T>, t: Ctx): Promise<T | undefined> {
  let err: unknown;
  let value: T | undefined;
  let okFlag = false;
  try {
    value = await fn();
    okFlag = true;
  } catch (e) {
    err = e;
  }
  if (!okFlag) {
    if (isThrottled(err)) {
      t.skip();
      return undefined;
    }
    throw err;
  }
  return value;
}

/** Expect a TranscriptError, skipping when the cause is throttling. */
async function failure(fn: () => Promise<unknown>, t: Ctx): Promise<TranscriptError | undefined> {
  let err: unknown;
  let succeeded = false;
  try {
    await fn();
    succeeded = true;
  } catch (e) {
    err = e;
  }
  if (succeeded) throw new Error("expected the request to fail, but it succeeded");
  if (isThrottled(err)) {
    t.skip();
    return undefined;
  }
  return err as TranscriptError;
}

/** Videos verified to exhibit the property each test relies on. */
const WITH_CAPTIONS = "dQw4w9WgXcQ"; // human English + auto English
const AUTO_ONLY = "XD4lDIuKxcc"; // auto-generated only
const NO_CAPTIONS = "FKYPIYRbDew"; // no caption tracks at all
const LIVE_24_7 = "jfKfPfyJRdk"; // endless stream, no captions
const FOREIGN = "Y9z5QkSQC1o"; // Thai auto-captions only
const GONE = "aaaaaaaaaaa"; // does not exist

const suite = describe.skipIf(!RUN);

if (!RUN) {
  describe("live suite", () => {
    it("is skipped unless RUN_LIVE=1", () => {
      expect(RUN).toBe(false);
    });
  });
}

suite("transcripts", () => {
  it("returns a human-written transcript for a known video", async (t) => {
    const result = await attempt(() => getTranscript({ url: "https://youtu.be/" + WITH_CAPTIONS, maxChars: 4000 }, cfg), t);
    if (!result) return;
    expect(result.ok).toBe(true);
    expect(result.videoId).toBe(WITH_CAPTIONS);
    expect(result.isAutoGenerated).toBe(false);
    expect(result.language).toBe("en");
    expect(result.segmentCount).toBeGreaterThan(10);
    expect(String(result.text)).toMatch(/strangers to love/i);
    await wait();
  });

  it("resolves a shared URL with playlist and timestamp noise", async (t) => {
    const result = await attempt(
      () => getTranscript({ url: "https://www.youtube.com/watch?v=" + WITH_CAPTIONS + "&list=RD" + WITH_CAPTIONS + "&t=30s", maxChars: 400 }, cfg),
      t,
    );
    if (!result) return;
    expect(result.videoId).toBe(WITH_CAPTIONS);
    expect(result.requestedStartSeconds).toBe(30);
    await wait();
  });

  it("falls back to auto-generated captions and says so", async (t) => {
    const result = await attempt(() => getTranscript({ url: AUTO_ONLY, maxChars: 1500 }, cfg), t);
    if (!result) return;
    expect(result.isAutoGenerated).toBe(true);
    expect(result.notes.join(" ")).toMatch(/auto-generated/i);
    await wait();
  });

  it("renders srt and segments", async (t) => {
    const srt = await attempt(() => getTranscript({ url: WITH_CAPTIONS, output: "srt", maxChars: 900 }, cfg), t);
    if (srt) expect(String(srt.text)).toMatch(/^\d+\n\d{2}:\d{2}:\d{2},\d{3} --> /);
    await wait();
    const segs = await attempt(() => getTranscript({ url: WITH_CAPTIONS, output: "segments", maxChars: 900 }, cfg), t);
    if (segs) {
      expect(Array.isArray(segs.segments)).toBe(true);
      expect(segs.segments![0]).toHaveProperty("startMs");
    }
    await wait();
  });

  it("reports truncation instead of silently cutting", async (t) => {
    const result = await attempt(() => getTranscript({ url: WITH_CAPTIONS, maxChars: 200 }, cfg), t);
    if (!result) return;
    expect(result.truncated).toBe(true);
    expect(result.totalChars).toBeGreaterThan(200);
    await wait();
  });
});

suite("when a transcript cannot be served", () => {
  it("says NO_TRANSCRIPT when the video has no captions", async (t) => {
    const err = await failure(() => getTranscript({ url: NO_CAPTIONS }, cfg), t);
    if (!err) return;
    expect(err.code).toBe("NO_TRANSCRIPT");
    expect(err.retryable).toBe(false);
    await wait();
  });

  it("explains auto-generated-only when they are excluded", async (t) => {
    const err = await failure(() => getTranscript({ url: AUTO_ONLY, includeAutoCaptions: false }, cfg), t);
    if (!err) return;
    expect(err.code).toBe("NO_TRANSCRIPT");
    expect(err.hint).toMatch(/includeAutoCaptions/);
    await wait();
  });

  it("lists alternatives when the language is missing", async (t) => {
    const err = await failure(() => getTranscript({ url: WITH_CAPTIONS, languages: ["xx"] }, cfg), t);
    if (!err) return;
    expect(err.code).toBe("LANGUAGE_UNAVAILABLE");
    expect(((err.details?.available ?? []) as unknown[]).length).toBeGreaterThan(0);
    await wait();
  });

  it("distinguishes a missing video from a missing transcript", async (t) => {
    const err = await failure(() => getTranscript({ url: "https://www.youtube.com/watch?v=" + GONE }, cfg), t);
    if (!err) return;
    expect(err.code).toBe("VIDEO_NOT_FOUND");
    await wait();
  });

  it("handles an endless live stream without inventing captions", async (t) => {
    const err = await failure(() => getTranscript({ url: LIVE_24_7 }, cfg), t);
    if (!err) return;
    expect(["LIVE_ENDED", "LIVE_NOT_STARTED", "NO_TRANSCRIPT", "VIDEO_UNAVAILABLE"]).toContain(err.code);
    await wait();
  });

  it("rejects a page rather than guessing a video", async (t) => {
    const err = await failure(() => getTranscript({ url: "https://www.youtube.com/playlist?list=PLbcLMApnBcdFL5lG2u2YpFpgIPWdovbBU" }, cfg), t);
    if (!err) return;
    expect(err.code).toBe("NOT_A_VIDEO_URL");
    await wait();
  });
});

suite("metadata tools", () => {
  it("lists languages including translation targets", async (t) => {
    const result = await attempt(() => listLanguages(WITH_CAPTIONS, cfg), t);
    if (!result) return;
    expect(result.hasCaptions).toBe(true);
    expect(result.tracks.some((x) => x.language === "en" && !x.autoGenerated)).toBe(true);
    expect(Array.isArray(result.translationLanguages)).toBe(true);
    await wait();
  });

  it("reports captionless videos as such", async (t) => {
    const info = await attempt(() => getVideoInfo(NO_CAPTIONS, cfg), t);
    if (!info) return;
    expect(info.captionsAvailable).toBe(false);
    expect(info.captionLanguages).toEqual([]);
    await wait();
  });

  it("reads a foreign-language video and translates on request", async (t) => {
    const native = await attempt(() => getTranscript({ url: FOREIGN, languages: ["th"], maxChars: 600 }, cfg), t);
    if (!native) return;
    expect(native.language).toBe("th");
    await wait(2000);
    const translated = await attempt(() => getTranscript({ url: FOREIGN, translateTo: "en", maxChars: 600 }, cfg), t);
    if (!translated) return;
    expect(translated.translatedTo).toBe("en");
    expect(translated.notes.join(" ")).toMatch(/translat/i);
    await wait();
  }, 90_000);
});
