/**
 * High-level operations behind the MCP tools.
 *
 * Everything the tools do is a small pipeline:
 *   parse the reference -> collect tracks from every provider that answers ->
 *   pick a language -> download through every URL that offers it -> render.
 * Each stage can fail in a well-understood way, and the error taxonomy turns
 * those failures into something an agent can act on.
 */

import { config as defaultConfig, type Config } from "./config.js";
import { collectTracks, downloadTranscript, fetchOEmbed, ytDlpAvailable, type CollectedTracks } from "./providers.js";
import { selectTrack, type CaptionTrack, type TranslationLanguage, type VideoDetails } from "./captions.js";
import { TranscriptError, toTranscriptError } from "./errors.js";
import {
  dedupeRollingCaptions,
  renderTranscript,
  type OutputFormat,
  type TranscriptSegment,
} from "./formats.js";
import { resolveVideoId, parseYouTubeTarget, type ParsedTarget } from "./url.js";

export interface TranscriptRequest {
  /** Any YouTube URL, or a bare 11-character video id. */
  url: string;
  /** Language preferences in priority order. Default: ["en", original]. */
  languages?: string[];
  /** Accept auto-generated (speech recognition) tracks. Default true. */
  includeAutoCaptions?: boolean;
  /** Output shape. Default "text". */
  output?: OutputFormat;
  /** Prefix text lines with [mm:ss]. Default false. */
  timestamps?: boolean;
  /** Truncate the returned text to this many characters. */
  maxChars?: number;
  /** Machine-translate the chosen track (YouTube translation) to this language. */
  translateTo?: string;
}

export interface TranscriptResult {
  ok: true;
  videoId: string;
  canonicalUrl: string;
  title?: string;
  author?: string;
  durationSeconds?: number;
  language: string;
  trackDisplayName: string;
  isAutoGenerated: boolean;
  translatedTo?: string;
  provider: string;
  providersTried: string[];
  segmentCount: number;
  format: OutputFormat;
  text?: string;
  segments?: TranscriptSegment[];
  truncated: boolean;
  totalChars?: number;
  notes: string[];
  requestedStartSeconds?: number;
}

export interface LanguageListResult {
  ok: true;
  videoId: string;
  canonicalUrl: string;
  title?: string;
  hasCaptions: boolean;
  autoTranslationAvailable: boolean;
  tracks: {
    language: string;
    displayName: string;
    autoGenerated: boolean;
    original?: boolean;
    source: string;
  }[];
  translationLanguages: TranslationLanguage[];
  providers: string[];
  notes: string[];
}

export interface VideoInfoResult {
  ok: true;
  videoId: string;
  canonicalUrl: string;
  title?: string;
  author?: string;
  durationSeconds?: number;
  isLive?: boolean;
  captionsAvailable: boolean;
  captionLanguages: string[];
  autoGeneratedOnly: boolean;
  providers: string[];
  parsed: ParsedTarget;
  notes: string[];
}

// ------------------------------------------------------------------ cache --

interface CacheEntry<T> {
  value: T;
  expires: number;
}

class TtlCache {
  private map = new Map<string, CacheEntry<any>>();
  constructor(private ttlMs: number, private max = 128) {}
  get(key: string): any | undefined {
    const hit = this.map.get(key);
    if (!hit) return undefined;
    if (hit.expires < Date.now()) {
      this.map.delete(key);
      return undefined;
    }
    return hit.value;
  }
  set(key: string, value: any): void {
    if (this.ttlMs <= 0) return;
    if (this.map.size >= this.max) this.map.delete(this.map.keys().next().value as string);
    this.map.set(key, { value, expires: Date.now() + this.ttlMs });
  }
  clear(): void {
    this.map.clear();
  }
}

const segmentCache = new TtlCache(defaultConfig.cacheTtlMs);
type SegmentJob = Promise<{ segments: TranscriptSegment[]; provider: string; track: CaptionTrack }>;
const inFlight = new Map<string, SegmentJob>();

/** Exposed for tests and long-running servers that want a clean slate. */
export function clearCaches(): void {
  segmentCache.clear();
  inFlight.clear();
}

// ---------------------------------------------------------------- helpers --

const DEFAULT_LANGUAGES = ["en"];

function languagePreferences(req: TranscriptRequest): string[] {
  const requested = (req.languages ?? [])
    .map((s) => String(s ?? "").trim())
    .filter(Boolean);
  const list = requested.length ? requested : DEFAULT_LANGUAGES;
  // "en,es" in a single argument is a common mistake; be forgiving.
  return list.flatMap((l) => l.split(/[,;]+/).map((s) => s.trim()).filter(Boolean));
}

function applyTranslate(track: CaptionTrack, target: string, available: TranslationLanguage[]): CaptionTrack {
  const u = new URL(track.baseUrl.startsWith("http") ? track.baseUrl : "https://www.youtube.com" + track.baseUrl);
  u.searchParams.set("tlang", target);
  const known = available.some((l) => l.languageCode.toLowerCase() === target.toLowerCase());
  if (!known && available.length) {
    throw new TranscriptError("LANGUAGE_UNAVAILABLE", "YouTube does not offer translation into " + target + " for this video.", {
      hint: "Pick one of the languages listed in translationLanguages, or request a track that already exists.",
      details: { requested: target, translationLanguages: available.slice(0, 40) },
    });
  }
  // languageCode deliberately stays the source language: sibling copies of the
  // same track are matched on it when a download has to be retried elsewhere.
  return {
    ...track,
    translatedTo: target,
    displayName: track.displayName + " (machine translation)",
    baseUrl: u.toString(),
  };
}

/** Fetch + cache the parsed segment list for one track. */
async function loadSegments(
  videoId: string,
  track: CaptionTrack,
  candidates: CaptionTrack[],
  cfg: Config,
): Promise<{ segments: TranscriptSegment[]; provider: string; track: CaptionTrack }> {
  const key = [videoId, track.languageCode.toLowerCase(), track.isGenerated ? "asr" : "manual", track.trackId ?? "", track.baseUrl.includes("tlang=") ? track.baseUrl : ""].join("|");
  const cached = segmentCache.get(key);
  if (cached) return cached;

  const existing = inFlight.get(key);
  const work: SegmentJob = existing ?? downloadTranscript(videoId, track, candidates, cfg);
  inFlight.set(key, work);
  try {
    const result = await work;
    const segments = dedupeRollingCaptions(result.segments);
    if (!segments.length) {
      throw new TranscriptError("NO_TRANSCRIPT", "The " + track.languageCode + " caption track exists but contains no speech.", {
        hint: "The caption file is empty (common on music videos with placeholder captions).",
        details: { videoId, language: track.languageCode },
      });
    }
    segmentCache.set(key, result);
    return result;
  } finally {
    inFlight.delete(key);
  }
}

// ------------------------------------------------------------ operations ---

/** Resolve a reference, list tracks, and confirm the video is usable. */
async function describeReference(rawUrl: string, cfg: Config): Promise<{ videoId: string; target: ParsedTarget; tracks: CollectedTracks }> {
  const target = resolveVideoId(rawUrl);
  const videoId = target.videoId!;
  const tracks = await collectTracks(videoId, cfg);
  return { videoId, target, tracks };
}

export async function getTranscript(req: TranscriptRequest, cfg: Config = defaultConfig): Promise<TranscriptResult> {
  try {
    const { videoId, target, tracks } = await describeReference(req.url, cfg);
    const wanted = languagePreferences(req);
    const translating = req.translateTo ? String(req.translateTo).trim() : undefined;

    // When translating, the language we want is the *output*, so accept any
    // starting track rather than demanding the video already carries it.
    const chosen = selectTrack(tracks.tracks, {
      languages: translating ? [...wanted, translating] : wanted,
      allowAutoGenerated: req.includeAutoCaptions !== false,
      fallbackToAny: Boolean(translating),
    });
    const notes = [...chosen.notes, ...target.notes];

    let track = chosen.track;
    const alreadyTarget = translating ? chosen.distance === 0 || chosen.track.languageCode.toLowerCase() === translating.toLowerCase() : false;
    if (translating && !alreadyTarget) {
      track = applyTranslate(track, translating, tracks.translationLanguages);
      notes.push("Machine-translated into " + translating + " by YouTube; expect imperfect wording.");
    } else if (translating && alreadyTarget) {
      notes.push("Native " + translating + " captions exist, so no translation was needed.");
    }

    let segments: TranscriptSegment[];
    let provider: string;
    try {
      ({ segments, provider } = await loadSegments(videoId, track, tracks.tracks, cfg));
    } catch (err) {
      const te = toTranscriptError(err);
      const recoverable = te.code === "PROVIDER_FAILED" || te.code === "PARSE_ERROR" || te.code === "TIMEOUT";
      if (!recoverable || !tracks.providersSkipped.length) throw te;
      // Ask the providers we skipped: their copy of the same track may sit behind
      // a URL this IP can actually reach.
      const more = await collectTracks(videoId, cfg, { only: tracks.providersSkipped, stopAfterFirstTracks: false });
      ({ segments, provider } = await loadSegments(videoId, track, [...tracks.tracks, ...more.tracks], cfg));
    }
    const format: OutputFormat = req.output ?? "text";
    const rendered = renderTranscript(segments, {
      format,
      timestamps: req.timestamps,
      videoId,
      maxChars: req.maxChars ?? cfg.maxChars,
    });

    if (rendered.truncated) {
      notes.push("Transcript truncated to " + (req.maxChars ?? cfg.maxChars) + " characters of " + rendered.totalChars + ".");
    }

    const result: TranscriptResult = {
      ok: true,
      videoId,
      canonicalUrl: target.canonicalUrl ?? "https://www.youtube.com/watch?v=" + videoId,
      title: tracks.details.title,
      author: tracks.details.author,
      durationSeconds: tracks.details.lengthSeconds,
      language: track.translatedTo ?? track.languageCode,
      trackDisplayName: track.displayName,
      isAutoGenerated: chosen.track.isGenerated,
      translatedTo: req.translateTo,
      provider,
      providersTried: tracks.providers,
      segmentCount: segments.length,
      format,
      truncated: rendered.truncated,
      totalChars: rendered.totalChars,
      notes,
      requestedStartSeconds: target.startSeconds,
    };
    if (format === "segments") result.segments = segments;
    else result.text = rendered.body;
    if (target.startSeconds) notes.push("URL pointed at " + target.startSeconds + "s; full transcript returned.");
    return result;
  } catch (err) {
    throw toTranscriptError(err);
  }
}

export async function listLanguages(url: string, cfg: Config = defaultConfig): Promise<LanguageListResult> {
  try {
    const { videoId, target, tracks } = await describeReference(url, cfg);
    const result: LanguageListResult = {
      ok: true,
      videoId,
      canonicalUrl: target.canonicalUrl ?? "https://www.youtube.com/watch?v=" + videoId,
      title: tracks.details.title,
      hasCaptions: tracks.tracks.length > 0,
      autoTranslationAvailable: tracks.autoTranslationEnabled,
      tracks: tracks.tracks
        .map((t) => ({
          language: t.languageCode,
          displayName: t.displayName,
          autoGenerated: t.isGenerated,
          original: t.isOriginal,
          source: t.source,
        }))
        .sort((a, b) => a.language.localeCompare(b.language) || Number(a.autoGenerated) - Number(b.autoGenerated)),
      translationLanguages: tracks.translationLanguages,
      providers: tracks.providers,
      notes: [...target.notes],
    };
    if (!result.hasCaptions) {
      result.notes.push("No caption tracks: this video has no transcript to fetch.");
    }
    return result;
  } catch (err) {
    throw toTranscriptError(err);
  }
}

export async function getVideoInfo(url: string, cfg: Config = defaultConfig): Promise<VideoInfoResult> {
  const target = parseYouTubeTarget(url);
  if (!target.videoId) throw toTranscriptError(new TranscriptError("NOT_A_VIDEO_URL", "That reference does not identify a single video."));
  const videoId = target.videoId;

  let tracks: CollectedTracks | undefined;
  let notes = [...target.notes];
  try {
    tracks = await collectTracks(videoId, cfg);
  } catch (err) {
    const te = toTranscriptError(err);
    if (te.code !== "NO_TRANSCRIPT" && te.code !== "PROVIDER_FAILED") throw te;
    notes.push(te.message);
    tracks = {
      tracks: [],
      translationLanguages: [],
      autoTranslationEnabled: false,
      details: {},
      provider: "none",
      providers: [],
      providersSkipped: [],
      confirmedCaptionless: te.code === "NO_TRANSCRIPT",
    };
    if (te.code === "NO_TRANSCRIPT") notes = notes.filter((n) => n !== te.message);
  }

  const details: VideoDetails = tracks.details ?? {};
  const oembed = details.title ? undefined : await fetchOEmbed(videoId, cfg);
  const languages = [...new Set(tracks.tracks.map((t) => t.languageCode))];
  const autoOnly = tracks.tracks.length > 0 && tracks.tracks.every((t) => t.isGenerated);

  if (!details.title && oembed?.title) notes.push("Title taken from oEmbed; player response was unavailable.");
  if (autoOnly) notes.push("Captions are auto-generated only, so wording may be inaccurate.");
  if (tracks.tracks.length === 0 && details.isCaptionable === false) notes.push("YouTube reports this video is not captionable.");
  if (await ytDlpAvailable(cfg)) notes.push("yt-dlp fallback is installed and available.");

  return {
    ok: true,
    videoId,
    canonicalUrl: target.canonicalUrl ?? "https://www.youtube.com/watch?v=" + videoId,
    title: details.title ?? oembed?.title,
    author: details.author ?? oembed?.authorName,
    durationSeconds: details.lengthSeconds,
    isLive: details.isLive,
    captionsAvailable: tracks.tracks.length > 0,
    captionLanguages: languages,
    autoGeneratedOnly: autoOnly,
    providers: tracks.providers,
    parsed: target,
    notes,
  };
}

export { parseYouTubeTarget };
