/**
 * MCP surface: four tools, each returning text a model can use directly plus
 * structured metadata where it helps.
 *
 * Failure design is the important part. "This video has no transcript" must not
 * look like a network error, and a language miss must tell the caller which
 * languages do exist, so the client can recover without a human.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { getTranscript, getVideoInfo, listLanguages, parseYouTubeTarget } from "./service.js";
import { isTranscriptError, toTranscriptError } from "./errors.js";
import { config, type Config } from "./config.js";

export const SERVER_NAME = "youtube-transcript";
export const SERVER_VERSION = "0.1.0";

export const INSTRUCTIONS = [
  "Fetches transcripts (captions) for YouTube videos.",
  "",
  "Start with youtube_get_transcript and pass the URL exactly as the user gave it;",
  "watch, youtu.be, shorts, live, embed, music and bare-id forms all work.",
  "",
  "Reading failures:",
  "- NO_TRANSCRIPT: the video genuinely has no captions. Do not retry; tell the user.",
  "- LANGUAGE_UNAVAILABLE: pick a language from details.available and ask again.",
  "- NOT_A_VIDEO_URL / INVALID_VIDEO_ID: the link was a playlist, channel, clip or a typo.",
  "- PRIVATE_VIDEO / MEMBERS_ONLY / AGE_RESTRICTED / REGION_RESTRICTED: access-limited, not retryable.",
  "- BOT_CHECK / RATE_LIMITED: YouTube is throttling this IP; retry later.",
  "",
  "Captions may be auto-generated (isAutoGenerated=true): warn the user the wording can be off.",
  "youtube_list_languages shows available tracks; youtube_video_info is a cheap availability check;",
  "youtube_parse_url explains how a link was interpreted without spending a network request.",
].join("\n");

const urlArg = z
  .string()
  .describe(
    "YouTube video reference: watch URL, youtu.be short link, /shorts/, /live/, /embed/, music.youtube.com, youtube-nocookie.com, an attribution link, or a bare 11-character video id.",
  );

const languageArg = z
  .array(z.string())
  .optional()
  .describe("Language preferences in priority order, e.g. [\"en\"] or [\"hi\", \"en\"]. Defaults to [\"en\"]. Falls back to the closest available track and says so in notes.");

const autoArg = z
  .boolean()
  .optional()
  .describe("Include YouTube auto-generated (speech-recognised) captions. Default true; set false to require human-written captions only.");

const json = (value: unknown): string => JSON.stringify(value, null, 2);

const text = (s: string): { type: "text"; text: string } => ({ type: "text" as const, text: s });

function failure(err: unknown): { content: { type: "text"; text: string }[]; isError: true } {
  const te = toTranscriptError(err);
  return { content: [text(json(te.toJSON()))], isError: true as const };
}

export function createServer(cfg: Config = config): McpServer {
  const server = new McpServer({ name: SERVER_NAME, version: SERVER_VERSION }, { instructions: INSTRUCTIONS });

  server.registerTool(
    "youtube_get_transcript",
    {
      title: "Get YouTube transcript",
      description: [
        "Return the transcript of a YouTube video, from any YouTube URL.",
        "Handles watch / youtu.be / shorts / live / embed / music / nocookie links and bare video ids.",
        "If the video has no captions it fails with code NO_TRANSCRIPT instead of inventing text;",
        "if the requested language is missing it fails with LANGUAGE_UNAVAILABLE plus the available list.",
        "Use output=segments for timestamped cues, or timestamps=true for [mm:ss] prefixed lines.",
      ].join(" "),
      inputSchema: {
        url: urlArg,
        languages: languageArg,
        includeAutoCaptions: autoArg,
        output: z
          .enum(["text", "srt", "vtt", "markdown", "segments"])
          .optional()
          .describe("Output shape: text (default, readable lines), markdown (timestamped bullets), segments (JSON with millisecond timings), or srt / vtt subtitle files."),
        timestamps: z.boolean().optional().describe("Prefix each line of text output with its [mm:ss] offset."),
        maxChars: z.number().int().positive().optional().describe("Truncate the transcript to roughly this many characters."),
        translateTo: z
          .string()
          .optional()
          .describe("Ask YouTube to machine-translate the selected captions into this language (for example es). Only works when the video offers translations."),
      },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async ({ url, languages, includeAutoCaptions, output, timestamps, maxChars, translateTo }) => {
      try {
        const result = await getTranscript({ url, languages, includeAutoCaptions, output, timestamps, maxChars, translateTo }, cfg);
        const { text: body, segments, ...meta } = result;
        return {
          content: [text(body ?? json(segments ?? []))],
          structuredContent: meta as unknown as Record<string, unknown>,
        };
      } catch (err) {
        if (!isTranscriptError(err)) throw err;
        return failure(err);
      }
    },
  );

  server.registerTool(
    "youtube_list_languages",
    {
      title: "List transcript languages",
      description: [
        "List every caption track a video offers, marking which are auto-generated.",
        "Use it after LANGUAGE_UNAVAILABLE, or to decide what youtube_get_transcript can return.",
        "hasCaptions=false means the video has no transcript at all.",
      ].join(" "),
      inputSchema: { url: urlArg },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async ({ url }) => {
      try {
        const result = await listLanguages(url, cfg);
        return { content: [text(json(result))], structuredContent: result as unknown as Record<string, unknown> };
      } catch (err) {
        if (!isTranscriptError(err)) throw err;
        return failure(err);
      }
    },
  );

  server.registerTool(
    "youtube_video_info",
    {
      title: "Inspect video and caption availability",
      description: [
        "Cheap report for one video: title, author, duration, whether captions exist and in which languages.",
        "Call it before a batch of transcript requests, or to explain why a transcript is missing.",
      ].join(" "),
      inputSchema: { url: urlArg },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async ({ url }) => {
      try {
        const result = await getVideoInfo(url, cfg);
        return { content: [text(json(result))], structuredContent: result as unknown as Record<string, unknown> };
      } catch (err) {
        if (!isTranscriptError(err)) throw err;
        return failure(err);
      }
    },
  );

  server.registerTool(
    "youtube_parse_url",
    {
      title: "Parse a YouTube URL",
      description: [
        "Offline parse of a YouTube reference: video id, playlist id, start offset and how it was recognised.",
        "Makes no network requests. Useful for validating a link and explaining playlist, channel or clip links.",
      ].join(" "),
      inputSchema: { url: z.string().describe("Any YouTube URL, or a bare 11-character video id.") },
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ url }) => {
      try {
        const parsed = parseYouTubeTarget(url);
        const payload = { ok: true, parsed };
        return { content: [text(json(payload))], structuredContent: payload as unknown as Record<string, unknown> };
      } catch (err) {
        if (!isTranscriptError(err)) throw err;
        return failure(err);
      }
    },
  );

  return server;
}
